# Generated by Django 2.2.6 on 2019-10-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128)),
                ('event_poster', models.ImageField(null=True, upload_to='event_posters/')),
                ('event_description', models.CharField(max_length=256)),
                ('event_date', models.DateField()),
                ('img1', models.ImageField(blank=True, upload_to='event_img/')),
                ('img2', models.ImageField(blank=True, upload_to='event_img/')),
                ('img3', models.ImageField(blank=True, upload_to='event_img/')),
                ('img4', models.ImageField(blank=True, upload_to='event_img/')),
                ('img5', models.ImageField(blank=True, upload_to='event_img/')),
                ('event_time', models.CharField(choices=[('f', 'Future'), ('n', 'Present'), ('p', 'Past')], default='f', max_length=1)),
                ('event_winners', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
